import mongoose from 'mongoose';

const TradeDataSchema = new mongoose.Schema({
  'HS CODE': { type: String },
  'Product Name': { type: String },
  'Product Category': { type: String },
  'Item Description': { type: String },
  'Grade': { type: String },
  'Grade Category': { type: String },
  'Origin': { type: String },
  'Origin2': { type: String },
  'Actual LC Date': { type: String },
  'LC Date': { type: String },
  'No. of Days - Shipment': { type: String },
  'Importer Category': { type: String },
  'Actual Importer Name': { type: String },
  'Importer Name': { type: String },
  'Imp Group': { type: String },
  'Importer Address': { type: String },
  'Agent Name': { type: String },
  'Actual Consignor Name': { type: String },
  'Consignor Name': { type: String },
  'Consignor Group': { type: String },
  'Consignor Group 12 Words': { type: String },
  'Assessed Value': { type: String },
  'Assessed Unit': { type: String },
  'DCL Unit': { type: String },
  'DCL Val': { type: String },
  'Qty (Kg)': { type: String },
  'Price/Kg': { type: String },
  'QTY (Mts)': { type: String },
  'Price/Mt': { type: String },
  'PT DUTY': { type: String },
  'PT STAX': { type: String },
  'PTSTAX': { type: String },
  'ITAXAT': { type: String },
  'Machine No.': { type: String },
  'Cash No': { type: String },
  'Cash Date': { type: String },
  'Month': { type: String },
  'Year': { type: String },
  'BE Type': { type: String },
  'Port': { type: String },
  'Port Name': { type: String },
}, {
  timestamps: true,
});

export default mongoose.models.TradeData || mongoose.model('TradeData', TradeDataSchema);